FROM mace015/laravel-docker-php-cli:latest

# Install vim, composer, nodejs, npm, git and mysql-client.
RUN apk add vim composer nodejs npm git mysql-client

WORKDIR /application

CMD ["tail", "-f", "/dev/null"]
