FROM mace015/laravel-docker-php-cli:latest

# Install composer, nodejs, npm, git and mysql-client.
RUN apk add composer nodejs npm git mysql-client

WORKDIR /application

CMD ["tail", "-f", "/dev/null"]
