version: '3.7'

services:
    webserver:
        image: nginx:alpine
        container_name: ${PROJECT_NAME}-webserver
        expose:
            - "80"
            - "443"
        volumes:
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ../:/application:cached
        environment:
            - VIRTUAL_HOST=${HOST_NAME}
            - LETSENCRYPT_HOST=${HOST_NAME}
            - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
            - VIRTUAL_PORT=80
        links:
            - application
        restart: unless-stopped
        networks:
            - application-network
    application:
        image: mace015/laravel-docker-application:latest
        container_name: ${PROJECT_NAME}-app
        volumes:
            - ../:/application:cached
        links: 
            - database
            - redis
        restart: unless-stopped
        networks:
            - application-network
    database:
        image: mariadb:latest
        container_name: ${PROJECT_NAME}-database
        volumes:
            - ./data/database:/var/lib/mysql:cached
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        restart: unless-stopped
        networks:
            - application-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: ${PROJECT_NAME}-phpmyadmin
        environment:
            - VIRTUAL_HOST=phpmyadmin.${HOST_NAME}
            - VIRTUAL_PORT=80
            - PMA_HOST=database
            - PMA_USER=root
            - PMA_PASSWORD=${DB_PASSWORD}
        links:
            - database
        restart: unless-stopped
        networks:
            - application-network
    redis:
        image: redis:alpine
        container_name: ${PROJECT_NAME}-redis
        restart: unless-stopped
        networks:
            - application-network
    workspace:
        image: mace015/laravel-docker-workspace:latest
        container_name: ${PROJECT_NAME}-workspace
        volumes:
            - ../:/application:cached
        links: 
            - database
        restart: unless-stopped
        networks:
            - application-network
    worker:
        image: mace015/laravel-docker-worker:latest
        container_name: ${PROJECT_NAME}-worker
        volumes:
            - ../:/application:cached
        links: 
            - database
            - redis
        restart: unless-stopped
        networks:
            - application-network
    cron:
        image: mace015/laravel-docker-cron:latest
        container_name: ${PROJECT_NAME}-cron
        volumes:
            - ../:/application:cached
        links:
            - database
            - redis
        restart: unless-stopped
        networks:
            - application-network

networks:
    application-network:
        external:
            name: ${PROJECT_NAME}-network
